# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52afc340e7d41504e06ad37876b665f03c6a0d8a8ac1c1bded0a5ead55a4fac3b298df741528d156151badc6c44f81be784a1f993bcf3c0bbedfa96dd333a52b

test:
  secret_key_base: b379dc638da6f1cafea88cbc178a6f39186fe7b39e0210fe09dbb8d2af8edfcacee9265f08213573560d73287c6eccee96c850a12cf7c567887769975311e836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
